version: "3.9"
services:
  fileuploader:
    build: .
    ports:
      - "5000:80"
    volumes:
      - /tmp/media:/app/upload
    environment:
      - auth_user=${auth_user}
      - auth_password=${auth_password}
      - base_url=${base_url}
      - allowed_content_types=${allowed_content_types}